functionsDirectory = "/Users/philsterr/Projects/ai_chat/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/philsterr/Projects/ai_chat/build/web"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/philsterr/Projects/ai_chat"
command = "flutter build web --release"
functions = "/Users/philsterr/Projects/ai_chat/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"